#!/usr/bin/env bash

# bash git prompt
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="verbose"

__git_ps1_improved() {
    local git_current_branch_name="\$(__git_ps1 '%s' | sed 's/ .\+//' | sed -e 's/[\\\\/&]/\\\\\\\\&/g')"
    local git_status_substitutes=(
        "s/$git_current_branch_name//;"            # remove branch temporarily
        "s/u//;"                                   # upstream
        "s/+\([0-9]\+\)/↑\1/;"                     # outgoing
        "s/-\([0-9]\+\)/↓\1/;"                     # incoming
        "s/%/?/;"                                  # untracked
        "s/+/✓/;"                                  # staged
        "s/*/✕/;"                                  # unstaged
        "s/\(.*\)/⑂ $git_current_branch_name\1/;"  # insert branch again
    )

    echo "\$(__git_ps1 '%s'| sed \"${git_status_substitutes[@]}\")"
}
