#!/usr/bin/env bash

# bash git prompt
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="verbose"

__git_ps1_improved() {
    local git_status_substitutes=(
        "s/|u=/ =/;"                                # equal to upstream
        "s/|u+\([0-9]\+\)-\([0-9]\+\)/ ↑\1↓\2/;"    # diverged from upstream
        "s/|u+\([0-9]\+\)/ ↑\1/;"                   # ahead of upstream
        "s/|u-\([0-9]\+\)/ ↓\1/;"                   # behind upstream
        "s/%/?/;"                                   # untracked
        "s/+/✓/;"                                   # staged
        "s/*/✕/;"                                   # unstaged
    )

    echo "⑂ \$(__git_ps1 '%s'| sed \"${git_status_substitutes[@]}\")"
}
